version: "3.5"
services:
    backup-mysql:
        build:
            context: .
            dockerfile: Dockerfile
            network: host
        container_name: backup-mysql
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - backup-mysql_log:/var/log
            - backup-mysql_data:/data
            - backup-mysql_app:/opt/apache-camel-engine
volumes:
    backup-mysql_log:
    backup-mysql_data:
    backup-mysql_app: